### ISSUE TITLE
## moduleNotFoundError

### ISSUE THREAD

**Issue by BobBranson** [batmanlab/ICML-2023-Route-interpret-repeat#1]
When running train_explainer_CUB, there's a bug. Below is error info 

Traceback (most recent call last):
  File "../codebase/train_explainer_CUB.py", line 5, in <module>
    from Explainer.experiments_explainer_CUB import train_glt
  File "/home/ICML-2023-Route-interpret-repeat/src/codebase/Explainer/experiments_explainer_CUB.py", line 17, in <module>
    from Explainer.concept_extractor import do_explain_class
**ModuleNotFoundError: No module named 'Explainer.concept_extractor'**

I can't find a file named "concep_extractor" in the folder "Explainer". Is this file missing?

**Comment by shantanu-ai** [comment]
Thanks for pointing out. Explainer.concept_extractor is an old function invoked by a redundant function which is not used in anywhere in the code. I have modified and removed the unwanted portions and it is working now.
